#!/bin/bash
#______________________________________________________________________________
#Author: Salih Emin <cerebrux.gr [at] gmail.com>
#Website: http://osarena.net
#Licence: GPL3 (http://www.gnu.org/licenses/gpl.html)
#Version: 1.0 (first rlease 19-07-11)
#Περιγραφή:
#Αυτό το εργαλείο χρησιμεύει για την πρώτη εκκίνηση δημιουργίας κλώνου του 
#αποθετηρίου του OSarena/Linux-Apps στον αρχικό κατάλογο του χρήστη.
#______________________________________________________________________________

#Διάφορα μηνύματα
WindowTitle=$"OSarena.net"
MessageProgressTitle=$"Repository Installer v1.0"
MessageIntro=$"Παρακλώ σιγουρευτείτε οτι έχετε εγκαταστήσει το GIT στο σύστημά σας \n Αν δεν είναι εγκατεστημένο, κάντε το τώρα χωρίς να κλείσετε αυτό το παράθυρο. \n Αφού το έχετε εγκαταστήσει πατήστε 'Εντάξει' "
MessageCreateFolder=$"# \n Δημιουργία αρχικού φακέλου 'OSarenaRepo' "
MessageIntoFolder=$"# \n Είσοδος στον φάκελο 'OSarenaRepo' "
MessageCloneRepo=$"# \n Λήψη αποθετηρίου OSarena"
MessageMakeBinUpdate=$"# \n Ενεργοποίηση του update-repo"
MessageCompleteRepo=$"# \n Ολοκλήρωση διεργασιών"
MessageEnd=$"Οι διεργασίες έχουν ολοκληρωθεί \n Πρακαλώ ελέγξτε τον φάκελο 
               'OSarenaRepo' "

#Εισαγωγικό μήνυμα
zenity --info \
       --title "$WindowTitle" \
       --width 100 \
       --text "$MessageIntro"

(
#Ακολουθούν οι εσωτερικές διεργασίες του πυρήνα του προγράμματος ---->
set -x
echo "10%" && \
#_________________________________________________________
echo "$MessageCreateFolder" && \
mkdir OSarenaRepo                     #Δημιουργία φακέλου
echo "30%" && \
sleep 2
#_________________________________________________________
echo "$MessageIntoFolder" && \
cd OSarenaRepo                                  #Είσοδος στον φάκελο
echo "60%" && \
sleep 2
#_________________________________________________________
echo "$MessageCloneRepo" && \
git clone git://github.com/osarena/Linux-Apps.git #Λήψη αποθετηρίου
echo "80%" && \
sleep 2
#_________________________________________________________
echo "$MessageMakeBinUpdate" && \
chmod 775 Linux-Apps/update-repo                         #Δημιουργία εκτελέσιμου update-repo
sleep 2
#_________________________________________________________
echo "$MessageCompleteRepo" && \
echo "99%" && \
sleep 2
set +x
#<----- Ολοκλήρωση εσωτερικών διεργασιών του πυρήνα του προγράμματος
) | $(zenity --width 300 \
           --height 150 \
           --progress \
           --percentage=1 \
           --title "$WindowTitle | $MessageProgressTitle" \
           --text=$"Εγκατάσταση του αποθετηρίου. Παρακλώ περιμένετε..." \
           --auto-close) 

zenity --info \
       --title "$WindowTitle" \
       --width 100 \
       --text "$MessageEnd"
